# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  jonnychipzblazorwasm:
    image: jonnychipzblazorwasm
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 4080:80
      - 5443:443
  